version: '3.2'
services:
  slave:
    image: distraught1/we-jenkins-slave
    build: .
    container_name: we-jenkins-slave
    command: -url <url> <secret> <node-name>
    privileged: true
    platform: linux/x86_64
  web:
    platform: linux/x86_64
  worker:
    platform: linux/x86_64
